import 'package:evently/modules/onboarding/pages/onboarding_info.dart';

class OnboardingItems {
List<OnboardingInfo>itemsLight =[
  OnboardingInfo(image: "assets/images/onboarding_L_two.png", title: "Find Events That Inspire You", descriptions: "Dive into a world of events crafted to fit your unique interests. Whether you're into live music, art workshops, professional networking, or simply discovering new experiences, we have something for everyone. Our curated recommendations will help you explore, connect, and make the most of every opportunity around you."),
  OnboardingInfo(image: "assets/images/onboarding_L_three.png", title: "Effortless Event Planning", descriptions: "Take the hassle out of organizing events with our all-in-one planning tools. From setting up invites and managing RSVPs to scheduling reminders and coordinating details, we’ve got you covered. Plan with ease and focus on what matters – creating an unforgettable experience for you and your guests."),
  OnboardingInfo(image: "assets/images/onboarding_L_four.png", title: "Connect with Friends & Share Moments", descriptions: "Make every event memorable by sharing the experience with others. Our platform lets you invite friends, keep everyone in the loop, and celebrate moments together. Capture and share the excitement with your network, so you can relive the highlights and cherish the memories."),
];
List<OnboardingInfo>itemsDark =[
  OnboardingInfo(image: "assets/images/onboarding_L_two.png", title: "Find Events That Inspire You", descriptions: "Dive into a world of events crafted to fit your unique interests. Whether you're into live music, art workshops, professional networking, or simply discovering new experiences, we have something for everyone. Our curated recommendations will help you explore, connect, and make the most of every opportunity around you."),
  OnboardingInfo(image: "assets/images/onboarding_D_three.png", title: "Effortless Event Planning", descriptions: "Take the hassle out of organizing events with our all-in-one planning tools. From setting up invites and managing RSVPs to scheduling reminders and coordinating details, we’ve got you covered. Plan with ease and focus on what matters – creating an unforgettable experience for you and your guests."),
  OnboardingInfo(image: "assets/images/onboarding_D_four.png", title: "Connect with Friends & Share Moments", descriptions: "Make every event memorable by sharing the experience with others. Our platform lets you invite friends, keep everyone in the loop, and celebrate moments together. Capture and share the excitement with your network, so you can relive the highlights and cherish the memories."),
];
}